# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20181022_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='added_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='mainApp.User'),
        ),
    ]
