# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 17:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20181022_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='users',
            field=models.ManyToManyField(related_name='trips', to='mainApp.User'),
        ),
        migrations.AddField(
            model_name='joins',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip_joins', to='mainApp.Trip'),
        ),
        migrations.AddField(
            model_name='joins',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_joins', to='mainApp.User'),
        ),
    ]
