# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-22 17:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_auto_20181022_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Joins',
            new_name='Join',
        ),
    ]
