# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-23 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0009_auto_20181022_1916'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mainApp.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='trip',
            name='added_by',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='trip',
        ),
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AddField(
            model_name='favorite',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='item_favorites', to='mainApp.Item'),
            preserve_default=False,
        ),
    ]
